// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZec9t8TbCj3uC1FTfGTmTSnCmG4s4h9Q',
    appId: '1:66037279464:web:43551ef5295b6a52b9775d',
    messagingSenderId: '66037279464',
    projectId: 'ai-operating-system-50c4b',
    authDomain: 'ai-operating-system-50c4b.firebaseapp.com',
    storageBucket: 'ai-operating-system-50c4b.firebasestorage.app',
    measurementId: 'G-2F6Q1YPCRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARIuxdJ_C5T0MabZlZMYrlIxi0dqS8rtI',
    appId: '1:66037279464:android:257bf0188608f528b9775d',
    messagingSenderId: '66037279464',
    projectId: 'ai-operating-system-50c4b',
    storageBucket: 'ai-operating-system-50c4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpBqA8NV6hYv2AaVVF3lccxsyrdJ5dYik',
    appId: '1:66037279464:ios:668bfc0c4e4c21dbb9775d',
    messagingSenderId: '66037279464',
    projectId: 'ai-operating-system-50c4b',
    storageBucket: 'ai-operating-system-50c4b.firebasestorage.app',
    iosBundleId: 'com.example.aiLifeOs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpBqA8NV6hYv2AaVVF3lccxsyrdJ5dYik',
    appId: '1:66037279464:ios:668bfc0c4e4c21dbb9775d',
    messagingSenderId: '66037279464',
    projectId: 'ai-operating-system-50c4b',
    storageBucket: 'ai-operating-system-50c4b.firebasestorage.app',
    iosBundleId: 'com.example.aiLifeOs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZec9t8TbCj3uC1FTfGTmTSnCmG4s4h9Q',
    appId: '1:66037279464:web:de97ea55b73a1cecb9775d',
    messagingSenderId: '66037279464',
    projectId: 'ai-operating-system-50c4b',
    authDomain: 'ai-operating-system-50c4b.firebaseapp.com',
    storageBucket: 'ai-operating-system-50c4b.firebasestorage.app',
    measurementId: 'G-7T2XH41Q5E',
  );
}
